### ISSUE TITLE
How to open files in Blender?

### ISSUE THREAD

**Issue by 3dcinetv** [leotorrez/ZZ-Model-Importer-Assets#7]
https://github.com/leotorrez/ZZ-Model-Importer-Assets/tree/main/PlayerCharacterData/Ellen
I can only see the text list of the coordinates.
How do I import this in Blender with their corresponding UVs?

**Comment by leotorrez** [comment]
The issue is unrelated to the repo. Tutorials and instructions of usage are not given here
